# Generated by Django 3.1.4 on 2020-12-23 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidders',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='bidders', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biddings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='auctioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
