# Generated by Django 3.1.4 on 2020-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201223_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
