# Generated by Django 3.1.4 on 2020-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_holder',
            field=models.CharField(default='', max_length=64),
        ),
    ]
