# Generated by Django 3.1.4 on 2020-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201224_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(default='images/no-image.png', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
