# Generated by Django 3.1.4 on 2020-12-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201225_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='images'),
        ),
    ]
