# Generated by Django 3.1.4 on 2020-12-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201225_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('listing', models.ManyToManyField(blank=True, related_name='category', to='auctions.Listing')),
            ],
        ),
    ]
