# Generated by Django 3.1.4 on 2020-12-27 12:17

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('auctions', '0018_auto_20201227_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
