# Generated by Django 3.1.4 on 2020-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20201228_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='images/no-image.png', upload_to='media/images/'),
        ),
    ]
